/* ErrorHandler.as
 *
 * Released under MIT license: http://www.opensource.org/licenses/mit-license.php
 * Copyright (C) 2013   Douwe A. van Twillert - Art & Technology, Saxion
 */


package nl.saxion.act.utils
{
	import flash.utils.Timer;
	import flash.utils.getTimer;

	import flash.text.TextField;
	import flash.text.TextFormat;

	import flash.events.Event;
	import flash.events.TimerEvent;
	import flash.events.ErrorEvent;
	import flash.events.MouseEvent;
	import flash.events.UncaughtErrorEvent;

	import flash.display.Sprite;

	/**
	 * Class that catches errors and displays the output on a textField on the stage. 
	 * @author Douwe A. van Twillert
	 */
	public class ErrorHandler
	{
		private static const   ERROR_WAIT_TIME_IN_MILLISECONDS : uint = 10000;  // 30000;
		private static const WARNING_WAIT_TIME_IN_MILLISECONDS : uint =  3000;  //  5000;

		private static var   _spriteOnStage     : Sprite;
		private static var   _errorTime         : int = getTimer() - ERROR_WAIT_TIME_IN_MILLISECONDS;
		private static var   _message           : String;
		private static var   _count             : uint = 0;
		private static var   _textfieldOnSprite : TextField;
		private static var   _timer             : Timer = new Timer( WARNING_WAIT_TIME_IN_MILLISECONDS, ERROR_WAIT_TIME_IN_MILLISECONDS / WARNING_WAIT_TIME_IN_MILLISECONDS );
		
		/**
		 * Registers all event and the uncaught error event (exceptions) handlers.
		 * @param	aSpriteOnStage	A sprite, should remain added to the stage, otherwise the errors are not visible.
		 */
        public static function registerErrorHandlers( spriteOnStage : Sprite ) : void
		{
			_spriteOnStage = spriteOnStage;
			_spriteOnStage.addEventListener(         ErrorEvent.ERROR          , handleErrorEvent );
			_spriteOnStage.addEventListener( UncaughtErrorEvent.UNCAUGHT_ERROR , handleError      );
			_spriteOnStage.loaderInfo.uncaughtErrorEvents.addEventListener( UncaughtErrorEvent.UNCAUGHT_ERROR, uncaughtErrorHandler );
		}


		/**
		 * Displays all details of an UncaughtErrorEvent.
		 *
		 * @param	event	The event which holds the information.
		 */
		public static function uncaughtErrorHandler( uncaughtErrorevent : UncaughtErrorEvent ) : void
        {
            if ( uncaughtErrorevent.error is Error ) {
				handleError( uncaughtErrorevent.error as Error );
            } else {
                displayError( "a non-Error, non-ErrorEvent type was thrown and uncaught\n" + uncaughtErrorevent.toString() );
			}
        }


		/**
		 * Displays all details of an error. The message, an explanation if available,
		 * name, id, text and eventual stack trace are displayed.
		 *
		 * @param	error	The error which holds the information.
		 */
		public static function handleError( error : Error ) : void
        {
			displayError( "message=" + error.message
			              + getErrorExplanation( error.errorID )
						  + "\n\nname=" + error.name
						  + "\n\nid="   + error.errorID
			              + getErrorText( error.errorID )
			              + "\n\nstack trace=" + error.getStackTrace() );
        }


		/**
		 * Displays all details of an error event. The message, an explanation if available,
		 * name, id, text and eventual stack trace are displayed.
		 *
		 * @param	error	The error which holds the information.
		 */
        public static function handleErrorEvent( errorEvent : ErrorEvent ) : void
        {
			displayError( "\nmessage=" + errorEvent.text
			              + getErrorExplanation( errorEvent.errorID )
						  + "\n\nid="  + errorEvent.errorID
			              + getErrorText( errorEvent.errorID )
			              + "\n\nevent Phase=" + errorEvent.eventPhase);
        }


		/**
		 * Displays an error. The errorMessage is a string generated by the programmer.
		 *
		 * @param	errorMessage	The errorMessage to be displayed.
		 */
		public static function displayError( errorMessage : String ) : void
        {
			if ( displayMessage( errorMessage ) ) {
				startMessageRemovalTimer( TimerEvent.TIMER_COMPLETE , "starting error timer" );
			}
		}
		
		
		/**
		 * Displays a warning. The warningMessage is a string generated by the programmer.
		 *
		 * @param	warningMessage	The warningMessage to be displayed.
		 */
		public static function displayWarning( errorMessage : String ) : void
        {
			if ( displayMessage( errorMessage ) ) {
				startMessageRemovalTimer( TimerEvent.TIMER , "starting warning timer" );
			}
		}
		
		
		/**
		 * @private functions
		 */
		// =================
		// Private functions
		// =================
		static private function startMessageRemovalTimer(  event : String , traceMessage : String ) : void
		{
			_timer.addEventListener( event, removeMessage );
			_timer.reset();
			_timer.start();
			trace( traceMessage );
		
		}


	    private static function displayMessage( message : String ) : Boolean
        {
			_count = ( message == _message ) ? _count + 1 : 1;
			if ( _spriteOnStage ) {
				if ( ( message != _message ) && ( ( _errorTime + ERROR_WAIT_TIME_IN_MILLISECONDS ) < getTimer() ) ) {
					trace( message );
					_errorTime = getTimer();
					_message = message;
					if ( _textfieldOnSprite ) {
						_spriteOnStage.removeChild( _textfieldOnSprite );
					}
					var textField : TextField   = new TextField();
					textField.autoSize          = "left";
					textField.multiline         = true;
					textField.width             = _spriteOnStage.width;
					textField.width             = 640;
					//textField.wordWrap          = true;
					textField.defaultTextFormat = new TextFormat( 'Verdana', 12, 0xAA3333 );
					textField.background        = true;
					textField.backgroundColor   = 0x00EEEEEE;
					textField.text              = _count + "\t" + message;
					
					_textfieldOnSprite                    = textField;
					_textfieldOnSprite.doubleClickEnabled = true;
					_textfieldOnSprite.addEventListener( MouseEvent.DOUBLE_CLICK, removeMessage );
					_spriteOnStage.addChild( _textfieldOnSprite );
				} else if ( _textfieldOnSprite ) {
					_textfieldOnSprite.text = _count + "\t" + _message;
				}
				return true;
			}
			return false;
        }


		public static function removeMessage( event : Object ) : void
        {
			if ( _textfieldOnSprite ) {
				trace( "removeWarning()");
				_spriteOnStage.removeChild( _textfieldOnSprite );
				_message           = "";
				_errorTime         = 0;
				_textfieldOnSprite = null;
				_timer.removeEventListener( TimerEvent.TIMER_COMPLETE , removeMessage );
				_timer.removeEventListener( TimerEvent.TIMER          , removeMessage );
				_timer.reset();
			}
		}
		
		

		private static function getErrorText( errorCode : int ) : String
		{
			for ( var index : String in errorCodes ) {
				if ( errorCodes[ index ][ 0 ] == errorCode )
					return "\n\ntext=" + errorCodes[ index ][ 1 ]
			}
			return "";
		}


		private static function getErrorExplanation( errorCode : int ) : String
		{
			for ( var index : String in errorCodes ) {
				if ( errorCodes[ index][ 0 ] == errorCode ) {
					return "\n\nexplanation=" + errorCodes[ index][ 2 ]
				}
			}
			return "";
		}
		
		private static var errorCodes : Array = [
			[ 1000, "The system is out of memory.", "Flash needs more memory to compile your code than your system has available.\n	Close some of the applications or processes running on your system." ],
			[ 1001, "The method %m is not implemented.", "" ],
			[ 1002, "The precision argument must be between 0 and 20; got %d", "You specified a value less than 0 or greater than 20 for the precision argument\n	of a method or property. Pass a value between 0 and 20 as a precision argument." ],
			[ 1003, "The radix argument must be between 2 and 36; got %d", "You passed a value less than 2 or greater than 36 for the radix argument of a\n	method or property. Pass a value between 2 and 36 as a radix argument." ],
			[ 1004, "A method of '%t' was invoked on an incompatible object.", "You tried to call a method that is not available to the specified object.This\n	error occurs when you have copied a prototype function from one object to\n	another, and then invoked it, but the target object is not the same type as the\n	original object. Ensure that the target object and original object are the same\n	type. See ECMAScript edition 3 chapter 15 for more details." ],
			[ 1005, "Array index is not an integer (%f)", "You tried to access a member of an array using an index value that is not an\n	integer. Pass only integers as index values for arrays." ],
			[ 1006, "Call attempted on an object that is not a function.", "This error occurs when you attempt to call a function that does not exist. Make\n	sure that you are calling the correct function, and that the API has not changed\n	from ActionScript 2.0. Also, make sure that you are using the correct object.\n	For example, you will see this error when you use the following code (because\n	the last line mistakingly calls the variable big instead of blg):\n\t\tvar blg:String = 'foo';\n\t\tvar big:Sprite = new Sprite();\n\t\tvar error:int = big.length();" ],
			[ 1007, "Instantiation attempted on a non-constructor.", "" ],
			[ 1008, "%n is ambiguous; more than one binding matches.", "" ],
			[ 1009, "null has no properties.", "An object that evaluates to null can have no properties. This error can occur in\n	some unexpected (though valid) situations. For example, consider the following\n	code, which creates a Sprite object. Since this Sprite object is never added to\n	the display list (via the addChild() method of a DisplayObjectContainer object),\n	then its stage property is set to null, and as such, its stage property cannot\n	have any properties. So the code generates the errror:\n\t\timport flash.display.Sprite;\n\t\tvar sprite1:Sprite = new Sprite();\n\t\tvar q:String = sprite1.stage.quality;" ],
			[ 1010, "undefined has no properties.", "This error can occur if you are trying to access a property of an object that\n	does not exist. For example:\n\t\tvar obj:Object = new Object();\n\t\tobj.a = 'foo';\n\t\ttrace(obj.b.prop);\n\t\tYou can also see this error because of a mispelling, for example in the following,\n	where mc represents a MovieClip object on the display list, and the stage\n	property is misspelled with a capital S (it should be stage):\n\t\t\ttrace(mc.Stage.quality);" ],
			[ 1011, "Method %m contained illegal opcode %d at offset %d.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1012, "The last instruction exceeded code size.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1013, "Cannot call OP_findproperty when scopeDepth is 0.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1014, "Class %n could not be found.", "" ],
			[ 1015, "Method %m cannot set default xml namespace", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1017, "Scope stack overflow.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1018, "Scope stack underflow.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1019, "Getscopeobject %d is out of bounds.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1020, "Code cannot fall off the end of a method.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1021, "At least one branch target was not on a valid instruction in the method", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1023, "Stack overflow.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1024, "Stack underflow.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1025, "An invalid register %d was accessed.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1026, "Slot %d exceeds slotCount=%d of %t.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1027, "Method_info %d exceeds method_count=%d.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1028, "Disp_id %d exceeds max_disp_id=%d of %t.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1029, "Disp_id %d is undefined on %t.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1030, "Stack depth unbalanced. %d != %d.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1031, "Scope depth unbalanced. %d != %d.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1032, "Cpool index %d out of range %d.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1033, "Cpool entry %d wrong type.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1034, "Type Coercion failed: cannot convert %a to %t", "" ],
			[ 1035, "Illegal super expression in method %m", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1037, "Cannot assign to a method %n on %t", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1038, "%n is already defined", "You cannot declare a variable or function with the same identfier name more than\n	once within the same scope. In ActionScript 3.0, different code blocks (such as\n	those used in two for loops in the same function definition) are considered to\n	be in the same scope. This error indicates that the ActionScript in the SWF is\n	invalid. If you believe that the file has not been corrupted, please report the\n	problem to Adobe." ],
			[ 1039, "Cannot verify method until it is referenced", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1040, "RHS of instanceof must be a Class or Function", "" ],
			[ 1041, "RHS of operator must be a Class", "" ],
			[ 1042, "Not an ABC file. major_version=%d minor_version=%d", "You are attempting to use an invalid file with the player: the tool that\n	generates the SWF may be out of date or the SWF itself may be corrupt." ],
			[ 1043, "Invalid code_length=%d", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1044, "MethodInfo-%d unsupported flags=%d", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1045, "Unsupported traits kind=%d", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1046, "MethodInfo-%d referenced before definition", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1047, "No Entry Point Found", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1049, "Prototype objects must be vanilla Objects", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1050, "Cannot convert %o to primitive.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1051, "Illegal early binding access to %t", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1052, "Invalid URI passed to %s function.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1053, "Illegal override of %n in %t", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1054, "Illegal range or target offsets in exception handler", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1055, "%S has no properties", "" ],
			[ 1056, "Cannot create property %n on %t", "" ],
			[ 1057, "%t may only contain methods", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1058, "Illegal operand type: %t must be %t", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1059, "ClassInfo-%d referenced before definition", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1060, "ClassInfo %d exceeds class_count=%d.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1061, "The value %1 cannot be converted to %2 without losing precision.", "This error appears if you attempt to assign a decimal number to a property that\n	has data type int.\n\t\tThis error also appears for out-of-range assignments, such as the following:\n\t\t\tvar m0:int = 2147483648; // int.MAX_VALUE == 2147483647\n\t\tYou can also see this error when using the bitwise left shift operator (<<). For\n	example, consider the following code:\n\t\t\tvar m0:uint = 0xFF;\n\t\t\tvar m1:uint = m0<<24;\n\t\tThe result of left shift operator (<<) is interpreted as a 32-bit two's complement\n	number with sign. In the example, the result is a negative value, which causes\n	the error when assigned to the uint typed property. A workaround is the following:\n\t\t\tvar m0:uint = 0xFF;\n\t\t\tvar m1:uint = uint(m0<<24);" ],
			[ 1063, "Argument count mismatch on %m. Expected %d, got %d", "" ],
			[ 1064, "Cannot call method %m as constructor", "" ],
			[ 1065, "Variable %n is not defined", "" ],
			[ 1066, "Function('function body') is not supported", "" ],
			[ 1067, "Native method %m has illegal method body", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1068, "%t and %t cannot be reconciled", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1069, "Property %n not found on %t and there is no default value", "" ],
			[ 1070, "Method %n not found on %t", "" ],
			[ 1071, "Function %m has already been bound to %t", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1072, "Disp_id 0 is illegal.", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1073, "Non-override method %m replaced because of duplicate disp_id %d", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1075, "Math is not a function", "" ],
			[ 1076, "Math is not a constructor", "" ],
			[ 1077, "Illegal read of write-only property %n on %t", "" ],
			[ 1078, "Illegal opcode/multiname combination: %d <%n>", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1079, "Native methods not allowed in loaded code", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1080, "Illegal value for namespace", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1082, "No default namespace has been set", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1083, "The prefix '%S' for element '%w' is not bound.", "" ],
			[ 1084, "Element or attribute ('%w') do not match QName production:\n	QName::=(NCName':')?NCName", "" ],
			[ 1085, "The element type '%S' must be terminated by the matching end-tag ''.", "" ],
			[ 1086, "The %s method works only on lists containing one item.", "" ],
			[ 1087, "Assignment to indexed XML is not allowed.", "" ],
			[ 1088, "The markup in the document following the root element must be well-formed.", "" ],
			[ 1089, "Assignment to lists with more than one item is not supported", "" ],
			[ 1090, "XML parser failure: element is malformed", "" ],
			[ 1091, "XML parser failure: Unterminated CDATA section", "" ],
			[ 1092, "XML parser failure: Unterminated XML declaration", "" ],
			[ 1093, "XML parser failure: Unterminated DOCTYPE declaration", "" ],
			[ 1094, "XML parser failure: Unterminated comment", "" ],
			[ 1095, "XML parser failure: Unterminated attribute", "" ],
			[ 1096, "XML parser failure: Unterminated element", "" ],
			[ 1097, "XML parser failure: Unterminated processing instruction", "" ],
			[ 1098, "Illegal prefix '%S' for 'no namespace'.", "" ],
			[ 1100, "Cannot supply flags when constructing one RegExp from another.", "" ],
			[ 1101, "Cannot verify method %m with unknown scope", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1102, "Illegal default value for type %n", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1103, "Class %n cannot extend final base class", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1104, "Attribute '%S' was already specified for element '%S'.", "" ],
			[ 1107, "The ABC data is corrupt, attempt to read out of bounds", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1108, "The OP_newclass opcode was used with the incorrect base class", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1109, "Attempt to directly call unbound function %m from method %m", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1110, "%n cannot extend %t", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1111, "%n cannot implement %t", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1112, "Argument count mismatch on class coercion. Expected 1, got %d", "" ],
			[ 1113, "OP_newactivation used in method without NEED_ACTIVATION flag", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1114, "OP_getglobalslot or OP_setglobalslot used with no global scope", "This error indicates that the ActionScript in the SWF is invalid. If you believe\n	that the file has not been corrupted, please report the problem to Adobe." ],
			[ 1115, "%n is not a constructor", "" ],
			[ 1116, "second argument to Function.prototype.apply must be an array", "" ],
			[ 1500, "Error opening file '%S'.", "" ],
			[ 1501, "Error writing to file '%S'.", "" ],
			[ 1502, "A script has executed for longer than 15 seconds.", "" ],
			[ 1503, "A script did not exit in a timely fashion and was terminated.", "" ],
			[ 1504, "End of file", "" ],
			[ 1505, "The string index %d is out of bounds; must be in range %d to %d.", "" ],
			[ 1506, "The range specified is invalid.", "" ],
			[ 1507, "Argument '%s' may not be null.", "" ],
			[ 1508, "The value specified for argument '%s' is invalid.", "" ],
			[ 1509, "There was an error decompressing the data.", "" ],
			[ 1510, "When the callback argument is a method of a class, the optional argument must be\n	null.", "" ],
			[ 2000, "No active security context.", "" ],
			[ 2001, "Too few arguments were specified; got %1, %2 expected.", "" ],
			[ 2002, "Operation attempted on invalid socket.", "" ],
			[ 2003, "Invalid socket port number specified.", "The valid range is 0 to 65535. For more information, see Socket Connections in\n	this language reference." ],
			[ 2004, "One of the parameters is invalid.", "" ],
			[ 2005, "Parameter %1 is of the incorrect type. Should be type %2.", "" ],
			[ 2006, "The supplied index is out of bounds.", "" ],
			[ 2007, "Parameter %1 must be non-null.", "" ],
			[ 2008, "Parameter %1 must be one of the accepted values.", "" ],
			[ 2009, "This method cannot be used on a text field with a style sheet.", "" ],
			[ 2010, "Local-with-filesystem SWF files are not permitted to use sockets.", "" ],
			[ 2011, "Socket connection failed to %1:%2.", "There is a network problem. Possibly a DNS name is not resolving or a TCP socket\n	is not connecting." ],
			[ 2012, "%1 class cannot be instantiated.", "" ],
			[ 2013, "Feature can only be used in Flash Authoring.", "" ],
			[ 2014, "Feature is not available at this time.", "The feature is not supported on this system." ],
			[ 2015, "Invalid BitmapData.", "" ],
			[ 2017, "Only trusted local files may cause the Flash Player to exit.", "" ],
			[ 2018, "System.exit is only available in the standalone Flash Player.", "" ],
			[ 2019, "Depth specified is invalid.", "" ],
			[ 2020, "MovieClips objects with different parents cannot be swapped.", "" ],
			[ 2021, "Object creation failed.", "" ],
			[ 2022, "Class %1 must inherit from DisplayObject to link to a symbol.", "" ],
			[ 2023, "Class %1 must inherit from Sprite to link to the root.", "" ],
			[ 2024, "An object cannot be added as a child of itself.", "" ],
			[ 2025, "The supplied DisplayObject must be a child of the caller.", "" ],
			[ 2026, "An error occurred navigating to the URL %1.", "Possibly the URL does not exist, the network connection has a problem, or the\n	URL is outside the security sandbox." ],
			[ 2027, "Parameter %1 must be a non-negative number; got %2.", "" ],
			[ 2028, "Local-with-filesystem SWF file %1 cannot access Internet URL %2.", "" ],
			[ 2029, "This URLStream object does not have a stream opened.", "" ],
			[ 2030, "End of file was encountered.", "" ],
			[ 2031, "Socket Error.", "A socket error occurred. For more information, see Socket Connections in this\n	language reference." ],
			[ 2032, "Stream Error.", "" ],
			[ 2033, "Key Generation Failed.", "" ],
			[ 2034, "An invalid digest was supplied.", "" ],
			[ 2035, "URL Not Found.", "" ],
			[ 2036, "Load Never Completed.", "" ],
			[ 2037, "Functions called in incorrect sequence, or earlier call was unsuccessful.", "" ],
			[ 2038, "File I/O Error.This error occurs when an application can't get file size,\n	creation date or modification data using the FileReference API.", "" ],
			[ 2039, "Invalid remote URL protocol. The remote URL protocol must be HTTP or HTTPS.", "" ],
			[ 2041, "Only one file browsing session may be performed at a time.", "" ],
			[ 2042, "The digest property is not supported by this load operation.", "" ],
			[ 2044, "Unhandled %1:.", "" ],
			[ 2046, "The loaded file did not have a valid signature.", "" ],
			[ 2047, "Security sandbox violation: %1: %2 cannot access %3.", "" ],
			[ 2048, "Security sandbox violation: %1 cannot load data from %2.", "" ],
			[ 2049, "Security sandbox violation: %1 cannot upload data to %2.", "" ],
			[ 2051, "Security sandbox violation: %1 cannot evaluate scripting URLs within %2\n	(allowScriptAccess is %3). Attempted URL was %4.", "" ],
			[ 2052, "Only String arguments are permitted for allowDomain and allowInsecureDomain.", "" ],
			[ 2053, "Security sandbox violation: %1 cannot clear an interval timer set by %2.", "" ],
			[ 2054, "The value of Security.exactSettings cannot be changed after it has been used.", "" ],
			[ 2055, "The print job could not be started.", "" ],
			[ 2056, "The print job could not be sent to the printer.", "" ],
			[ 2057, "The page could not be added to the print job.", "The addPage() method is not used correctly. See the addPage() entry in this\n	language reference." ],
			[ 2058, "There was an error decompressing the data.", "" ],
			[ 2059, "Security sandbox violation: %1 cannot overwrite an ExternalInterface callback\n	added by %2.", "" ],
			[ 2060, "Security sandbox violation: ExternalInterface caller %1 cannot access %2.", "" ],
			[ 2061, "No ExternalInterface callback %1 registered.", "" ],
			[ 2062, "Children of Event must override clone() {return new MyEventClass (...);}.", "" ],
			[ 2063, "Error attempting to execute IME command.", "One of the IME services has failed.\n\t\tIf you are using the setConversionMode() or setEnabled() method, ActionScript 3.0\n	replaces these methods with the access property.\n\t\tIf you are using the doConversion() or setComposition() method, these methods are\n	not supported for Macintosh OSX." ],
			[ 2065, "The focus cannot be set for this target.", "" ],
			[ 2066, "The Timer delay specified is out of range.", "" ],
			[ 2067, "The ExternalInterface is not available in this container. ExternalInterface\n	requires Internet Explorer ActiveX, Firefox, Mozilla 1.7.5 and greater, or other\n	browsers that support NPRuntime.", "" ],
			[ 2068, "Invalid sound.", "" ],
			[ 2069, "The Loader class does not implement this method.", "" ],
			[ 2070, "Security sandbox violation: caller %1 cannot access Stage owned by %2.", "" ],
			[ 2071, "The Stage class does not implement this property or method.", "" ],
			[ 2073, "There was a problem saving the application to disk.", "Possibly you do not have write permission or there is not enough disk space." ],
			[ 2074, "The stage is too small to fit the download ui.", "" ],
			[ 2075, "The downloaded file is invalid.", "Possibly the file decompression failed, the file format is invalid, or the\n	signature validation failed." ],
			[ 2077, "This filter operation cannot be performed with the specified input parameters.", "" ],
			[ 2078, "The name property of a Timeline-placed object cannot be modified.", "" ],
			[ 2079, "Classes derived from Bitmap can only be associated with defineBits characters\n	(bitmaps).", "" ],
			[ 2082, "Connect failed because the object is already connected.", "" ],
			[ 2083, "Close failed because the object is not connected.", "" ],
			[ 2084, "The AMF encoding of the arguments cannot exceed 40K.", "" ],
			[ 2085, "Parameter %1 must be non-empty string.", "" ],
			[ 2086, "A setting in the mms.cfg file prohibits this FileReference request.", "" ],
			[ 2087, "The FileReference.download() file name contains prohibited characters.", "The filename cannot contain spaces or any of the following characters: /, \, :,\n	*, ?, ', <, >, |, %, or the ASCII control characters 0 through 31 (0x00 through\n	0X1F). Also, filenames longer than 256 characters may fail on some browsers or\n	servers." ],
			[ 2088, "The Proxy class does not implement getProperty. It must be overridden by a\n	subclass.", "" ],
			[ 2089, "The Proxy class does not implement setProperty. It must be overridden by a\n	subclass.", "" ],
			[ 2090, "The Proxy class does not implement callProperty. It must be overridden by a\n	subclass.", "" ],
			[ 2091, "The Proxy class does not implement hasProperty. It must be overridden by a\n	subclass.", "" ],
			[ 2092, "The Proxy class does not implement deleteProperty. It must be overridden by a\n	subclass.", "" ],
			[ 2093, "The Proxy class does not implement getDescendants. It must be overridden by a\n	subclass.", "" ],
			[ 2094, "Event dispatch recursion overflow.", "The recursion exceeds the maximum recursion depth. (The default maximum is 256.)" ],
			[ 2095, "%1 was unable to invoke callback %2.", "" ],
			[ 2096, "The HTTP request header %1 cannot be set via ActionScript.", "You are adding a disallowed HTTP header to an HTTP request. See the\n	flash.net.URLRequestHeader class for a complete list of disallowed HTTP request\n	headers." ],
			[ 2097, "The FileFilter Array is not in the correct format.", "There are two valid formats:\n\t\t\tA description with Windows file extensions only\n\t\t\tA description with Windows file extensions and Macintosh file formats.\n\t\tThe two file formats and not interchangeable; you must use one or the other. For\n	more information, see the FileFilter class in this language reference." ],
			[ 2098, "The loading object is not a .swf file, you cannot request SWF properties from\n	it.", "" ],
			[ 2099, "The loading object is not sufficiently loaded to provide this information.", "" ],
			[ 2100, "The ByteArray parameter in Loader.loadBytes() must have length greater than 0.", "" ],
			[ 2101, "The String passed to URLVariables.decode() must be a URL-encoded query string\n	containing name/value pairs.", "" ],
			[ 2102, "The before XMLNode parameter must be a child of the caller.", "" ],
			[ 2103, "XML recursion failure: new child would create infinite loop.", "Possibly you are trying to make objects child objects of each other. For\n	example, the following code generates this error because a and b both try to add\n	the other as a child object.\n\t\t\ta.addChild(b);\n\t\t\tb.addChild(a);" ],
			[ 2105, "The Proxy class does not implement nextNameIndex. It must be overridden by a\n	subclass.", "" ],
			[ 2106, "The Proxy class does not implement nextName. It must be overridden by a\n	subclass.", "" ],
			[ 2107, "The Proxy class does not implement nextValue. It must be overridden by a\n	subclass.", "" ],
			[ 2108, "Scene %1 was not found.", "" ],
			[ 2109, "Frame label %1 not found in scene %2.", "" ],
			[ 2110, "The value of Security.disableAVM1Loading cannot be set unless the caller can\n	access the stage and is in an ActionScript 3.0 SWF file.", "" ],
			[ 2111, "Security.disableAVM1Loading is true so the current load of the ActionScript\n	1.0/2.0 SWF file has been blocked.", "" ],
			[ 2112, "Provided parameter LoaderContext.ApplicationDomain is from a disallowed domain.", "" ],
			[ 2113, "Provided parameter LoaderContext.SecurityDomain is from a disallowed domain.", "" ],
			[ 2114, "Parameter %1 must be null.", "" ],
			[ 2115, "Parameter %1 must be false.", "" ],
			[ 2116, "Parameter %1 must be true.", "" ],
			[ 2118, "The LoaderInfo class does not implement this method.", "" ],
			[ 2119, "Security sandbox violation: caller %1 cannot access LoaderInfo.applicationDomain\n	owned by %2.", "" ],
			[ 2121, "Security sandbox violation: %1: %2 cannot access %3. This may be worked around\n	by calling Security.allowDomain.", "" ],
			[ 2122, "Security sandbox violation: %1: %2 cannot access %3. A policy file is required,\n	but the checkPolicyFile flag was not set when this media was loaded.", "" ],
			[ 2123, "Security sandbox violation: %1: %2 cannot access %3. No policy files granted\n	access.", "" ],
			[ 2124, "Loaded file is an unknown type.", "" ],
			[ 2125, "Security sandbox violation: %1 cannot use Runtime Shared Library %2 because\n	crossing the boundary between ActionScript 3.0 and ActionScript 1.0/2.0 objects\n	is not allowed.", "" ],
			[ 2126, "NetConnection object must be connected.", "" ],
			[ 2127, "FileReference POST data cannot be type ByteArray.", "" ],
			[ 2129, "Connection to %1 failed.", "" ],
			[ 2130, "Unable to flush SharedObject.", "" ],
			[ 2131, "Definition %1 cannot be found.", "" ],
			[ 2132, "NetConnection.connect cannot be called from a netStatus event handler.", "" ],
			[ 2133, "Callback %1 is not registered.", "" ],
			[ 2134, "Cannot create SharedObject.", "" ],
			[ 2136, "The SWF file %1 contains invalid data.", "" ],
			[ 2137, "Security sandbox violation: %1 cannot navigate window %2 within %3\n	(allowScriptAccess is %4). Attempted URL was %5.", "" ],
			[ 2138, "Rich text XML could not be parsed.", "" ],
			[ 2139, "SharedObject could not connect.", "" ],
			[ 2140, "Security sandbox violation: %1 cannot load %2. Local-with-filesystem and\n	local-with-networking SWF files cannot load each other.", "" ],
			[ 2141, "Only one PrintJob may be in use at a time.", "" ],
			[ 2142, "Security sandbox violation: local SWF files cannot use the\n	LoaderContext.securityDomain property. %1 was attempting to load %2.", "" ],
			[ 2143, "AccessibilityImplementation.get_accRole() must be overridden from its default.", "" ],
			[ 2144, "AccessibilityImplementation.get_accState() must be overridden from its default.", "" ],
			[ 2145, "Cumulative length of requestHeaders must be less than 8192 characters.", "" ],
			[ 2146, "Security sandbox violation: %1 cannot call %2 because the HTML/container\n	parameter allowNetworking has the value %3.", "" ],
			[ 2147, "Forbidden protocol in URL %1.", "" ],
			[ 2148, "SWF file %1 cannot access local resource %2. Only local-with-filesystem and\n	trusted local SWF files may access local resources.", "" ],
			[ 2149, "Security sandbox violation: %1 cannot make fscommand calls to %2\n	(allowScriptAccess is %3).", "" ],
			[ 2150, "An object cannot be added as a child to one of it's children (or children's\n	children, etc.).", "" ],
			[ 2151, "You cannot enter full screen mode when the settings dialog is visible.", "" ],
			[ 2152, "Full screen mode is not allowed.", "" ],
			[ 2153, "The URLRequest.requestHeaders array must contain only non-NULL URLRequestHeader\n	objects.", "" ],
			[ 2154, "The NetStream Object is invalid. This may be due to a failed NetConnection.", "" ],
			[ 2155, "The ExternalInterface.call functionName parameter is invalid. Only alphanumeric\n	characters are supported.", "" ],
			[ 2156, "Port %1 may not be accessed using protocol %2. Calling SWF was %3.", "" ],
			[ 2157, "Rejecting URL %1 because the 'asfunction:' protocol may only be used for link\n	targets, not for networking APIs.", "" ],
			[ 2158, "The NetConnection Object is invalid. This may be due to a dropped NetConnection.", "" ],
			[ 2159, "The SharedObject Object is invalid.", "" ],
			[ 2160, "The TextLine is INVALID and cannot be used to access the current state of the\n	TextBlock.", "" ],
			[ 2161, "An internal error occured while laying out the text.", "" ],
			[ 2162, "The Shader output type is not compatible for this operation.", "" ],
			[ 2163, "The Shader input type %1 is not compatible for this operation.", "" ],
			[ 2164, "The Shader input %1 is missing or an unsupported type.", "" ],
			[ 2165, "The Shader input %1 does not have enough data.", "" ],
			[ 2166, "The Shader input %1 lacks valid dimensions.", "" ],
			[ 2167, "The Shader does not have the required number of inputs for this operation.", "" ],
			[ 2168, "Static text lines have no atoms and no reference to a text block.", "" ],
			[ 2169, "The method %1 may not be used for browser scripting. The URL %2 requested by %3\n	is being ignored. If you intend to call browser script, use navigateToURL\n	instead.", "" ],
			[ 2170, "Security sandbox violation: %1 cannot send HTTP headers to %2.", "" ],
			[ 2171, "The Shader object contains no byte code to execute.", "" ],
			[ 2172, "The ShaderJob is already running or finished.", "" ],
			[ 2173, "Unable to read object in stream. The class %1 does not implement\n	flash.utils.IExternalizable but is aliased to an externalizable class.", "" ],
			[ 2174, "Only one download, upload, load or save operation can be active at a time on\n	each FileReference.", "" ],
			[ 2175, "One or more elements of the content of the TextBlock has a null ElementFormat.", "" ],
			[ 2176, "Certain actions, such as those that display a pop-up window, may only be invoked\n	upon user interaction, for example by a mouse click or button press.", "" ],
			[ 2177, "The Shader input %1 is too large.", "" ],
			[ 2178, "The Clipboard.generalClipboard object must be used instead of creating a new\n	Clipboard.", "" ],
			[ 2179, "The Clipboard.generalClipboard object may only be read while processing a\n	flash.events.Event.PASTE event.", "" ],
			[ 2180, "It is illegal to move AVM1 content (AS1 or AS2) to a different part of the\n	displayList when it has been loaded into AVM2 (AS3) content.", "" ],
			[ 2181, "The TextLine class does not implement this property or method.", "" ],
			[ 2182, "Invalid fieldOfView value. The value must be greater than 0 and less than 180.", "" ],
			[ 2183, "Scale values must not be zero.", "" ],
			[ 2184, "The ElementFormat object is locked and cannot be modified.", "" ],
			[ 2185, "The FontDescription object is locked and cannot be modified.", "" ],
			[ 2186, "Invalid focalLength %1.", "" ],
			[ 2187, "Invalid orientation style %1. Value must be one of 'Orientation3D.EULER_ANGLES',\n	'Orientation3D.AXIS_ANGLE', or 'Orientation3D.QUATERNION'.", "" ],
			[ 2188, "Invalid raw matrix. Matrix must be invertible.", "" ],
			[ 2189, "A Matrix3D can not be assigned to more than one DisplayObject.", "" ],
			[ 2190, "The attempted load of %1 failed as it had a Content-Disposition of attachment\n	set.", "" ],
			[ 2191, "The Clipboard.generalClipboard object may only be written to as the result of\n	user interaction, for example by a mouse click or button press.", "" ],
			[ 2192, "An unpaired Unicode surrogate was encountered in the input.", "" ],
			[ 2193, "Security sandbox violation: %1: %2 cannot access %3.", "" ],
			[ 2200, "The SystemUpdater class is not supported by this player.", "" ],
			[ 2201, "The requested update type is not supported on this operating system.", "" ],
			[ 2202, "Only one SystemUpdater action is allowed at a time.", "" ],
			[ 2203, "The requested SystemUpdater action cannot be completed.", "" ],
			[ 2204, "This operation cannot be canceled because it is waiting for user interaction.", "" ],
			[ 2205, "Invalid update type %1.", "" ],
			[ 3000, "Illegal path name.", "" ],
			[ 3001, "File or directory access denied.", "" ],
			[ 3002, "File or directory exists.", "" ],
			[ 3003, "File or directory does not exist.", "" ],
			[ 3004, "Insufficient file space.", "" ],
			[ 3005, "Insufficient system resources.", "" ],
			[ 3006, "Not a file.", "" ],
			[ 3007, "Not a directory.", "" ],
			[ 3008, "Read-only or write-protected media.", "" ],
			[ 3009, "Cannot move file or directory to a different device.", "" ],
			[ 3010, "Directory is not empty.", "" ],
			[ 3011, "Move or copy destination already exists.", "" ],
			[ 3012, "Cannot delete file or directory.", "" ],
			[ 3013, "File or directory is in use.", "" ],
			[ 3014, "Cannot copy or move a file or directory to overwrite a containing directory.", "" ],
			[ 3015, "Loader.loadBytes() is not permitted to load content with executable code.", "" ],
			[ 3016, "No application was found that can open this file.", "" ],
			[ 3100, "A SQLConnection cannot be closed while statements are still executing.", "" ],
			[ 3101, "Database connection is already open.", "" ],
			[ 3102, "Name argument specified was invalid. It must not be null or empty.", "" ],
			[ 3103, "Operation cannot be performed while there is an open transaction on this\n	connection.", "" ],
			[ 3104, "A SQLConnection must be open to perform this operation.", "" ],
			[ 3105, "Operation is only allowed if a connection has an open transaction.", "" ],
			[ 3106, "Property cannot be changed while SQLStatement.executing is true.", "" ],
			[ 3107, "%1 may not be called unless SQLResult.complete is false.", "" ],
			[ 3108, "Operation is not permitted when the SQLStatement.text property is not set.", "" ],
			[ 3109, "Operation is not permitted when the SQLStatement.sqlConnection property is not\n	set.", "" ],
			[ 3110, "Operation cannot be performed while SQLStatement.executing is true.", "" ],
			[ 3111, "An invalid schema type was specified.", "Valid values are: SQLIndexSchema, SQLTableSchema, SQLTriggerSchema SQLViewSchema" ],
			[ 3112, "An invalid transaction lock type was specified.", "Valid values are:\n\t\tSQLTransactionLockType.DEFERRED\n\t\tSQLTransactionLockType.IMMEDIATE\n\t\tSQLTransactionLockType.EXCLUSIVE" ],
			[ 3113, "Reference specified is not of type File.", "" ],
			[ 3114, "An invalid open mode was specified.", "Valid values are:\n\t\tSQLMode.READ\n\t\tSQLMode.UPDATE\n\t\tSQLMode.CREATE" ],
			[ 3115, "SQL Error.", "" ],
			[ 3116, "An internal logic error occurred.", "" ],
			[ 3117, "Access permission denied.", "Indicates that the operation failed because a SQL statement attempted to perform\n	an operation that it didn't have permission to perform, such as specifying an\n	INSERT operation to be performed on a view." ],
			[ 3118, "Operation aborted.", "Indicates that a SQL statement execution failed because execution was aborted.\n	This error occurs when code in a trigger cancels the operation using the SQL\n	RAISE() function, or if the SQLConnection.cancel() or SQLStatement.cancel()\n	methods are called when a statement is executed using SQLStatement.execute() or\n	SQLStatement.next() with a prefetch argument specified, and not all of the\n	results have been returned." ],
			[ 3119, "Database file is currently locked.", "" ],
			[ 3120, "Table is locked.", "Indicates that an operation could not be completed because another AIR\n	application was holding a lock on a table involved in the operation. This can\n	occur when a statement executing through a SQLConnection attempts to write to a\n	table when another SQLConnection (in the same application or a different\n	application) has an open transaction and is writing to the table, or if a\n	SQLConnection attempts to read from or write to a table while another\n	SQLConnection has an exclusive-locked transaction." ],
			[ 3121, "Out of memory.", "" ],
			[ 3122, "Attempt to write a readonly database.", "Indicates that an operation could not be completed because the database is read\n	only. This can occur if the database file is designated as read only in the\n	operating system, if the database is opened in read-only mode, or if an older\n	version of Adobe AIR accesses a database file created with a newer version of\n	the runtime." ],
			[ 3123, "Database disk image is malformed.", "Indicates that the operation failed because the specified file is a database\n	file whose data has become corrupted. This can happen when the application is\n	force quit while in a transaction or any other time that a database file is left\n	in the state of having an open transaction that can't be rolled back when\n	reopening the file." ],
			[ 3124, "Insertion failed because database is full.", "" ],
			[ 3125, "Unable to open the database file.", "Indicates that the connection could not be completed because the database file\n	could not be opened. This can happen if SQLConnection.open() or\n	SQLConnection.openAsync()is called with the openMode parameter set to\n	SQLMode.UPDATE and the database file doesn't exist. It can also happen if the\n	operating system returns an error when the runtime attempts to access the\n	database file." ],
			[ 3126, "Database lock protocol error.", "" ],
			[ 3127, "Database is empty.", "" ],
			[ 3128, "Disk I/O error occurred.", "Indicates that an operation could not be completed because of a disk I/O error.\n	This can happen if the runtime is attempting to delete a temporary file and\n	another program (such as a virus protection application) is holding a lock on\n	the file. This can also happen if the runtime is attempting to write data to a\n	file and the data can't be written." ],
			[ 3129, "The database schema changed.", "Indicates that the operation could not be completed because of a schema error.\n	This occurs when the schema of the database changes after a statement is\n	prepared but before it finishes executing, such as if two SQLConnection\n	instances are connected to the same database, and one instance changes the\n	schema while another one is reading it." ],
			[ 3130, "Too much data for one row of a table.", "" ],
			[ 3131, "Abort due to constraint violation.", "Indicates that the operation could not be completed because the statement caused\n	a violation of one or more data integrity constraints. These are constraints\n	that are defined in the table structure when it is created. For more\n	information, see the CREATE TABLE section in the appendix SQL support in local\n	databases." ],
			[ 3132, "Data type mismatch.", "Indicates that the operation could not be completed because of a data type\n	mismatch error. This occurs when the data type of a value doesn't match the\n	expected or required type. For more information, see the Data type support\n	section in the appendix SQL support in local databases." ],
			[ 3133, "An internal error occurred.", "" ],
			[ 3134, "Feature not supported on this operating system.", "" ],
			[ 3135, "Authorization denied.", "" ],
			[ 3136, "Auxiliary database format error.", "" ],
			[ 3137, "An index specified for a parameter was out of range.", "Indicates that the operation could not be completed because a parameter index\n	was not valid, such as if a parameter is specified with an index less than 0, or\n	if a parameter is specified with index 7 but the statement text only includes\n	five parameters." ],
			[ 3138, "File opened is not a database file.", "" ],
			[ 3139, "The page size specified was not valid for this operation.", "" ],
			[ 3140, "The encryption key size specified was not valid for this operation. Keys must be\n	exactly 16 bytes in length", "" ],
			[ 3141, "The requested database configuration is not supported.", "" ],
			[ 3143, "Unencrypted databases may not be reencrypted.", "" ],
			[ 3200, "Cannot perform operation on closed window.", "" ],
			[ 3201, "Adobe Reader cannot be found.", "" ],
			[ 3202, "Adobe Reader 8.1 or later cannot be found.", "" ],
			[ 3203, "Default Adobe Reader must be version 8.1 or later.", "" ],
			[ 3204, "An error ocurred trying to load Adobe Reader.", "" ],
			[ 3205, "Only application-sandbox content can access this feature.", "" ],
			[ 3206, "Caller %1 cannot set LoaderInfo property %2.", "" ],
			[ 3207, "Application-sandbox content cannot access this feature.", "" ],
			[ 3208, "Attempt to access invalid clipboard.", "" ],
			[ 3209, "Attempt to access dead clipboard.", "" ],
			[ 3210, "The application attempted to reference a JavaScript object in a HTML page that\n	is no longer loaded.", "" ],
			[ 3211, "Drag and Drop File Promise error: %1", "" ],
			[ 3212, "Cannot perform operation on a NativeProcess that is not running.", "" ],
			[ 3213, "Cannot perform operation on a NativeProcess that is already running.", "" ],
			[ 3214, "NativeProcessStartupInfo.executable does not specify a valid executable file.", "" ],
			[ 3215, "NativeProcessStartupInfo.workingDirectory does not specify a valid directory.", "" ],
			[ 3216, "Error while reading data from NativeProcess.standardOutput.", "" ],
			[ 3217, "Error while reading data from NativeProcess.standardError.", "" ],
			[ 3218, "Error while writing data to NativeProcess.standardInput.", "" ],
			[ 3219, "The NativeProcess could not be started. '%1'", "" ],
			[ 3220, "Action '%1' not allowed in current security context '%2'.", "" ],
			[ 3221, "Adobe Flash Player cannot be found.", "" ],
			[ 3222, "The installed version of Adobe Flash Player is too old.", "" ],
			[ 3223, "DNS lookup error: platform error %1", "" ],
			[ 3224, "Socket message too long", "" ],
			[ 3225, "Cannot send data to a location when connected.", "" ],
			[ 3226, "Cannot import a SWF file when LoaderContext.allowCodeImport is false.", "" ],
			[ 3300, "Voucher is invalid.", "Reacquire the voucher from the server." ],
			[ 3301, "User authentication failed.", "Ask user to re-enter credentials." ],
			[ 3302, "Flash Access server does not support SSL.", "SSL must be enabled on the license server when playing content packaged using\n	Flash Media Right Management Server." ],
			[ 3303, "Content expired.", "Reacquire voucher from the server." ],
			[ 3304, "User authorization failed (for example, the user has not purchased the content).", "The current user is not authorized to view the content." ],
			[ 3305, "Can't connect to the server.", "Check the network connection." ],
			[ 3306, "Client update required (Flash Access server requires new client).", "Both the runtime (Flash Player or AIR) and the Flash Access module need to be\n	updated." ],
			[ 3307, "Generic internal Flash Access failure.", "" ],
			[ 3308, "Wrong voucher key.", "Reacquire the voucher from the server." ],
			[ 3309, "Video content is corrupted.", "Try downloading the content again." ],
			[ 3310, "The AIR application or Flash Player SWF does not match the one specified in the\n	DRM policy.", "" ],
			[ 3311, "The version of the application does not match the one specified in the DRM\n	policy.", "" ],
			[ 3312, "Verification of voucher failed.", "Reacquire the voucher from the server." ],
			[ 3313, "Write to the file system failed.", "" ],
			[ 3314, "Verification of FLV/F4V header file failed.", "Try downloading the DRMContentData object again. If DRMContentData was extracted\n	from FLV/F4V try downloading the content again." ],
			[ 3315, "The current security context does not allow this operation.", "This error can occur when the remote SWF loaded by AIR isn't allowed access to\n	Flash Access functionality. This error can also occur if a security error occurs\n	during network access. Other possible security errors include errors due to a\n	crossdomain.xml file, which restricts client access based on domain, or if\n	crossdomain.xml is not accessible." ],
			[ 3316, "The value of LocalConnection.isPerUser cannot be changed because it has already\n	been locked by a call to LocalConnection.connect, .send, or .close.", "" ],
			[ 3317, "Failed to load Flash Access module.", "If this error occurs in AIR, reinstall AIR. If this error occurs in Flash\n	Player, download the Flash Access module again." ],
			[ 3318, "Incompatible version of Flash Access module found.", "If this error occurs in AIR, reinstall AIR. If this error occurs in Flash\n	Player, download the Flash Access module again." ],
			[ 3319, "Missing Flash Access module API entry point.", "If this error occurs in AIR, reinstall AIR. If this error occurs in Flash\n	Player, download the Flash Access module again." ],
			[ 3320, "Generic internal Flash Access failure.", "" ],
			[ 3321, "Individualization failed.", "There was a problem with the Adobe server (e.g. could be busy). Retry the\n	operation." ],
			[ 3322, "Device binding failed.", "Undo any device changes or reset the license (voucher) files. The Flash Access\n	module will then reindividualize. In AIR, voucher reset can be done by invoking\n	the resetDRMVouchers() on DRMManager, whereas in Flash Player, the user needs to\n	reset the license files in the Flash Player Settings Manager." ],
			[ 3323, "The internal stores are corrupted.", "Retry the operation. If the error persists, reset the license files in the Flash\n	Player Settings Manager. The Flash Access module will then reindividualize." ],
			[ 3324, "Reset license files and the client will fetch a new machine token.", "Reset the license files in the Flash Player Settings Manager and the client will\n	fetch a new machine token." ],
			[ 3325, "Internal stores are corrupt.", "Internal stores are corrupt and has been deleted. Retry the operation." ],
			[ 3326, "Call customer support.", "Tampering has been detected. Options are to call customer support, or reset the\n	license files in the Flash Player Settings Manager." ],
			[ 3327, "Clock tampering detected.", "Options are to reacquire the voucher or to fix the clock." ],
			[ 3328, "Server error; retry the request.", "This error is a server error. Retry the request. The sub error gives the error\n	returned by the server." ],
			[ 3329, "Error in application-specific namespace.", "The server has returned an error in an application-specific namespace. Check the\n	application for details." ],
			[ 3330, "Need to authenticate the user and reacquire the voucher.", "Try authenticating the user and acquiring the voucher again." ],
			[ 3331, "Content is not yet valid.", "The voucher is not yet valid. Try again at a later date." ],
			[ 3332, "Cached voucher has expired. Reacquire the voucher from the server.", "The voucher cached on the local computer has expired. Reacquire the voucher from\n	the server." ],
			[ 3333, "The playback window for this policy has expired.", "The playback window for this policy has expired. The user can no longer play\n	this content under this policy." ],
			[ 3334, "This platform is not allowed to play this content.", "This platform is not allowed to play this media." ],
			[ 3335, "Invalid version of Flash Access module. Upgrade AIR or Flash Access module for\n	the Flash Player.", "In AIR, update to the latest version of AIR. In Flash Player, upgrade to the\n	latest version of the Flash Access module and try playing content again." ],
			[ 3336, "This platform is not allowed to play this content.", "This operating system is not allowed to play this media." ],
			[ 3337, "Upgrade Flash Player or AIR and retry playback.", "Upgrade to the latest version of AIR or Flash Player, and try playing content\n	again." ],
			[ 3338, "Unknown connection type.", "Flash Player or AIR cannot detect the connection type. Try connecting the device\n	to a different connection." ],
			[ 3339, "Can't play back on analog device. Connect to a digital device.", "Cannot play media on an analog device. Connect to a digital device and try\n	again." ],
			[ 3340, "Can't play back because connected analog device doesn't have the correct\n	capabilities.", "Cannot play media because the connected analog device doesn't have the correct\n	capabilities (for example, it doesn't have Macrovision or ACP)." ],
			[ 3341, "Can't play back on digital device.", "The policy does not allow play back on digital devices." ],
			[ 3342, "The connected digital device doesn't have the correct capabilities.", "The connected digital device doesn't have the correct capabilities, for example,\n	it doesn't support HDCP." ],
			[ 3343, "Internal Error.", "If this error occurs in AIR, reinstall AIR. If this error occurs in Flash\n	Player, download the Flash Access module." ],
			[ 3344, "Missing Flash Access module.", "If this error occurs in AIR, reinstall AIR. If this error occurs in Flash\n	Player, download the Flash Access module." ],
			[ 3345, "This operation is not permitted with content protected using Flash Access.", "" ],
			[ 3400, "An error occured while executing JavaScript code.", "" ],
			[ 3401, "Security sandbox violation: An object with this name has already been registered\n	from another security domain.", "" ],
			[ 3402, "Security sandbox violation: Bridge caller %1 cannot access %2.", "" ]
		];
	}
}